# Challenge Author: 
name: web_login

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build Docker Image
        run: |
            docker build -t web_login -f examples/web_automation/challenge/Dockerfile .

      - name: Run Docker container
        run: |
            docker run --rm -d 1341:1341 --name web_login web_login

      - name: Run Python scripts
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          pytest examples/web_automation/challenge
        env:
          CONTAINER_HOST: localhost


      - name: Clean up Docker container
        run: |
            docker stop web_login
